# Generated by Django 3.0.8 on 2020-07-25 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_costsheetname_embroidery_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsheetname',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
