# Generated by Django 3.0.8 on 2020-07-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_costsheetname_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='embroidery',
            name='related',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.CostSheetName'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='related',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.CostSheetName'),
        ),
    ]
