# Generated by Django 3.0.8 on 2020-07-26 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('src', '0004_auto_20200726_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadType', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=100, null=True)),
                ('tktSize', models.CharField(max_length=100, null=True)),
                ('cost_unit', models.CharField(max_length=100, null=True)),
                ('extraAllowance', models.CharField(max_length=100, null=True)),
                ('importDuty', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('supplier', models.CharField(max_length=100, null=True)),
                ('holder', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.CostSheetName')),
            ],
        ),
        migrations.CreateModel(
            name='PolyBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyBagType', models.CharField(max_length=100, null=True)),
                ('polyBagMaterial', models.CharField(max_length=100, null=True)),
                ('dimension', models.CharField(max_length=100, null=True)),
                ('cost_unit', models.CharField(max_length=100, null=True)),
                ('extraAllowance', models.CharField(max_length=100, null=True)),
                ('totalCost', models.CharField(max_length=100, null=True)),
                ('importDuty', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('supplier', models.CharField(max_length=100, null=True)),
                ('holder', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.CostSheetName')),
            ],
        ),
        migrations.CreateModel(
            name='MainLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelType', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('extraAllowance', models.CharField(max_length=100, null=True)),
                ('totalCost', models.CharField(max_length=100, null=True)),
                ('importDuty', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('supplier', models.CharField(max_length=100, null=True)),
                ('holder', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.CostSheetName')),
            ],
        ),
        migrations.CreateModel(
            name='CMT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmtCost', models.CharField(max_length=100, null=True)),
                ('packagingCharge', models.CharField(max_length=100, null=True)),
                ('factoryOverheadCost', models.CharField(max_length=100, null=True)),
                ('testingCost', models.CharField(max_length=100, null=True)),
                ('otherCost', models.CharField(max_length=100, null=True)),
                ('logisticCost', models.CharField(max_length=100, null=True)),
                ('factoryMarkup', models.CharField(max_length=100, null=True)),
                ('totalInr', models.CharField(max_length=100, null=True)),
                ('agentMarkup', models.CharField(max_length=100, null=True)),
                ('factoryFOB', models.CharField(max_length=100, null=True)),
                ('clientFOB', models.CharField(max_length=100, null=True)),
                ('constractualCost', models.CharField(max_length=100, null=True)),
                ('holder', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.CostSheetName')),
            ],
        ),
    ]
