# Generated by Django 3.0.8 on 2020-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_thread_threadcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='consumption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
