# Generated by Django 3.0.8 on 2020-07-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_thread_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='totalCost',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
